<html>
    <head>
        <script src="jquery.js" type="text/javascript" />
        <script type="text/javascript">
            
            $('div#jogo').load(url);
            
        </script>
    </head>
    <body>
        <div id="baralho">
            <h2>Baralho</h2>
            <p></p>
        </div>
        <div id="jogador1">
            <h2>Jogador 1</h2>
            <p></p>
        </div>
        <div id="jogador2">
            <h2>Jogador 2</h2>
            <p></p>
        </div>
        <div id="descarte">
            <h2>Descarte</h2>
            <p></p>
        </div>
    </body>
</html>