<?php
namespace App\Model;

/** 
 * Generated by PHPUnit_SkeletonGenerator on 2012-08-31 at 02:17:11.
 * @author Helison Teixeira <helisonreus@gmail.com>
 * @version 0.1
 * 
 */
class JogadorTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var Jogador
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new Jogador;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers App\Model\Jogador::getId
     *
     */
    public function testGetId()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers App\Model\Jogador::setId
     * @todo   Implement testSetId().
     */
    public function testSetId()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers App\Model\Jogador::getEscolha
     * @todo   Implement testGetEscolha().
     */
    public function testGetEscolha()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers App\Model\Jogador::setEscolha
     * @todo   Implement testSetEscolha().
     */
    public function testSetEscolha()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers App\Model\Jogador::getCartas
     * @todo   Implement testGetCartas().
     */
    public function testGetCartas()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers App\Model\Jogador::setCartas
     * @todo   Implement testSetCartas().
     */
    public function testSetCartas()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers App\Model\Jogador::addCartas
     * @todo   Implement testAddCartas().
     */
    public function testAddCartas()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers App\Model\Jogador::count
     * @todo   Implement testCount().
     */
    public function testCount()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }
}
