<?php
namespace App\Model;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2012-08-31 at 02:17:11.
 */
class JogoTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var Jogo
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new Jogo;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers App\Model\Jogo::getBaralho
     * @todo   Implement testGetBaralho().
     */
    public function testGetBaralho()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers App\Model\Jogo::getDescarte
     * @todo   Implement testGetDescarte().
     */
    public function testGetDescarte()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers App\Model\Jogo::escolher
     * @todo   Implement testEscolher().
     */
    public function testEscolher()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers App\Model\Jogo::getCarta
     * @todo   Implement testGetCarta().
     */
    public function testGetCarta()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers App\Model\Jogo::isPar
     * @todo   Implement testIsPar().
     */
    public function testIsPar()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers App\Model\Jogo::addCartaDescarte
     * @todo   Implement testAddCartaDescarte().
     */
    public function testAddCartaDescarte()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers App\Model\Jogo::obterDescarte
     * @todo   Implement testObterDescarte().
     */
    public function testObterDescarte()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers App\Model\Jogo::getTurno
     * @todo   Implement testGetTurno().
     */
    public function testGetTurno()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers App\Model\Jogo::trocarTurno
     * @todo   Implement testTrocarTurno().
     */
    public function testTrocarTurno()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers App\Model\Jogo::getJogador
     * @todo   Implement testGetJogador().
     */
    public function testGetJogador()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers App\Model\Jogo::getJogador1
     * @todo   Implement testGetJogador1().
     */
    public function testGetJogador1()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers App\Model\Jogo::getJogador2
     * @todo   Implement testGetJogador2().
     */
    public function testGetJogador2()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }
}
